paths = set(
    [
        "/standard-page.html",
        "/theme.css",
        "/main.css",
        "/config.json",
        "/favicon.svg",
        "/use.css",
        "/convert/index.html",
        "/convert/main.js",
        "/icons/arrows.svg",
        "/icons/minecart_loaded.svg",
        "/icons/speedometer.svg",
        "/icons/hourglass_split.svg",
        "/icons/beaker.svg",
        "/icons/c-circle.svg",
        "/icons/aspect_ratio.svg",
        "/icons/thermometer.svg",
        "/icons/x.svg",
        "/icons/x_lg.svg",
        "/icons/rulers.svg.html",
        "/icons/rulers.svg",
        "/use/use.js",
        "/foo/foo.css",
        "/foo/bar.css",
        "/convert copy/index.html",
        "/convert copy/main.js",
        "/error/error.css",
        "/error/error.jinja",
        "/error/error.js",
        "/error/error.svg",
        "/error/error.json",
        "/error/error.html",
        "/error/error.txt",
    ]
)
